-- 支付系统增强迁移脚本

-- 1. 在支付订单表中添加点数更新状态字段
ALTER TABLE ai_images_creator_payments 
ADD COLUMN IF NOT EXISTS credits_updated BOOLEAN DEFAULT FALSE;

-- 2. 添加订单处理历史表
CREATE TABLE IF NOT EXISTS ai_images_creator_payment_process_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(50) NOT NULL, -- 订单号
  process_type VARCHAR(50) NOT NULL, -- 处理类型：webhook, check, manual, fix-public, schedule
  status VARCHAR(20) NOT NULL, -- 处理结果：success, failed
  details JSONB, -- 处理详情，如错误信息、处理结果等
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 添加订单号索引
CREATE INDEX IF NOT EXISTS idx_payment_process_history_order_no 
ON ai_images_creator_payment_process_history(order_no);

-- 添加处理时间索引
CREATE INDEX IF NOT EXISTS idx_payment_process_history_created_at 
ON ai_images_creator_payment_process_history(created_at);

-- 添加行级安全策略
ALTER TABLE ai_images_creator_payment_process_history ENABLE ROW LEVEL SECURITY;

-- 创建服务端可查看和管理所有记录的策略
CREATE POLICY "Service role can manage all payment process history"
  ON ai_images_creator_payment_process_history
  USING (auth.jwt() ->> 'role' = 'service_role');

-- 3. 添加支付回调日志表
CREATE TABLE IF NOT EXISTS ai_images_creator_payment_callbacks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(50) NOT NULL, -- 订单号
  raw_data TEXT, -- 原始回调数据
  parsed_data JSONB, -- 解析后的回调数据
  process_result VARCHAR(50), -- 处理结果：received, success, failed, skipped
  error_message TEXT, -- 错误信息
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  ip_address VARCHAR(50) -- 回调请求的IP地址
);

-- 添加订单号索引
CREATE INDEX IF NOT EXISTS idx_payment_callbacks_order_no 
ON ai_images_creator_payment_callbacks(order_no);

-- 添加回调时间索引
CREATE INDEX IF NOT EXISTS idx_payment_callbacks_created_at 
ON ai_images_creator_payment_callbacks(created_at);

-- 添加行级安全策略
ALTER TABLE ai_images_creator_payment_callbacks ENABLE ROW LEVEL SECURITY;

-- 创建服务端可查看和管理所有记录的策略
CREATE POLICY "Service role can manage all payment callbacks"
  ON ai_images_creator_payment_callbacks
  USING (auth.jwt() ->> 'role' = 'service_role');

-- 4. 添加支付操作日志表
CREATE TABLE IF NOT EXISTS ai_images_creator_payment_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_no VARCHAR(50) NOT NULL, -- 订单号
  user_id VARCHAR(50), -- 用户ID
  process_type VARCHAR(50) NOT NULL, -- 操作类型：check, fix, fix-public
  status VARCHAR(20) NOT NULL, -- 操作状态：pending, success, failed
  details JSONB, -- 操作详情
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 添加订单号索引
CREATE INDEX IF NOT EXISTS idx_payment_logs_order_no 
ON ai_images_creator_payment_logs(order_no);

-- 添加用户ID索引
CREATE INDEX IF NOT EXISTS idx_payment_logs_user_id 
ON ai_images_creator_payment_logs(user_id);

-- 添加操作时间索引
CREATE INDEX IF NOT EXISTS idx_payment_logs_created_at 
ON ai_images_creator_payment_logs(created_at);

-- 添加行级安全策略
ALTER TABLE ai_images_creator_payment_logs ENABLE ROW LEVEL SECURITY;

-- 创建服务端可查看和管理所有记录的策略
CREATE POLICY "Service role can manage all payment logs"
  ON ai_images_creator_payment_logs
  USING (auth.jwt() ->> 'role' = 'service_role'); 