-- ai_images_creator_credits.sql
-- 创建用户点数表
CREATE TABLE IF NOT EXISTS ai_images_creator_credits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  credits INTEGER NOT NULL DEFAULT 5,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  
  CONSTRAINT unique_user_id UNIQUE (user_id)
);

-- 添加行级安全策略
ALTER TABLE ai_images_creator_credits ENABLE ROW LEVEL SECURITY;

-- 创建只允许用户查看自己记录的策略
CREATE POLICY "Users can view their own credits"
  ON ai_images_creator_credits
  FOR SELECT
  USING (auth.uid() = user_id);

-- 创建允许插入新记录的策略
CREATE POLICY "New users can insert their initial credits"
  ON ai_images_creator_credits
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 创建允许用户更新自己记录的策略
CREATE POLICY "Users can update their own credits"
  ON ai_images_creator_credits
  FOR UPDATE
  USING (auth.uid() = user_id);

-- 创建触发器函数，在用户注册时自动添加初始点数
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.ai_images_creator_credits (user_id, credits)
  VALUES (NEW.id, 5);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 创建触发器，在用户注册后自动执行
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 创建或更新点数增加函数
CREATE OR REPLACE FUNCTION increment_user_credits(user_id_param UUID, credits_to_add INT)
RETURNS VOID AS $$
DECLARE
  current_credits INT;
BEGIN
  -- 获取用户当前点数
  SELECT credits INTO current_credits
  FROM ai_images_creator_credits
  WHERE user_id = user_id_param
  ORDER BY created_at DESC
  LIMIT 1;
  
  -- 如果没有记录，默认为0
  IF current_credits IS NULL THEN
    current_credits := 0;
  END IF;
  
  -- 创建新的点数记录
  INSERT INTO ai_images_creator_credits (
    user_id,
    credits,
    operation,
    reason
  ) VALUES (
    user_id_param,
    current_credits + credits_to_add,
    'refund',
    '任务取消退款'
  );
END;
$$ LANGUAGE plpgsql;

-- 为增加用户点数函数添加安全策略
REVOKE ALL ON FUNCTION increment_user_credits FROM PUBLIC;
GRANT EXECUTE ON FUNCTION increment_user_credits TO service_role;