-- ai_images_creator_history.sql
-- 创建用户图片生成历史记录表
CREATE TABLE IF NOT EXISTS ai_images_creator_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  prompt TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  
  -- 可选：添加其他相关字段
  model_used TEXT,
  generation_settings JSONB,
  status TEXT DEFAULT 'completed'
);

-- 添加行级安全策略
ALTER TABLE ai_images_creator_history ENABLE ROW LEVEL SECURITY;

-- 创建只允许用户查看自己记录的策略
CREATE POLICY "Users can view their own image history"
  ON ai_images_creator_history
  FOR SELECT
  USING (auth.uid() = user_id);

-- 创建允许插入新记录的策略
CREATE POLICY "Users can insert new image records"
  ON ai_images_creator_history
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 可选：创建索引以提高查询性能
CREATE INDEX idx_ai_images_creator_history_user_id ON ai_images_creator_history(user_id);
CREATE INDEX idx_ai_images_creator_history_created_at ON ai_images_creator_history(created_at);