-- ai_images_creator_history.sql
-- 创建用户图片生成历史记录表
CREATE TABLE IF NOT EXISTS ai_images_creator_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL CHECK (image_url ~ '^https?://.+'),
  prompt TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  
  -- 可选：添加其他相关字段
  model_used TEXT,
  style TEXT,
  aspect_ratio TEXT,
  standard_aspect_ratio TEXT,
  generation_settings JSONB,
  status TEXT DEFAULT 'completed',
  
  -- 添加URL有效性检查
  CONSTRAINT valid_image_url CHECK (
    image_url ~ '^https?://[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}(/\S*)?$'
  )
);

-- 添加行级安全策略
ALTER TABLE ai_images_creator_history ENABLE ROW LEVEL SECURITY;

-- 创建只允许用户查看自己记录的策略
CREATE POLICY "Users can view their own image history"
  ON ai_images_creator_history
  FOR SELECT
  USING (auth.uid() = user_id);

-- 创建允许插入新记录的策略
CREATE POLICY "Users can insert new image records"
  ON ai_images_creator_history
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- 创建允许用户更新自己记录的策略
CREATE POLICY "Users can update their own image records"
  ON ai_images_creator_history
  FOR UPDATE
  USING (auth.uid() = user_id);

-- 创建允许用户删除自己记录的策略
CREATE POLICY "Users can delete their own image records"
  ON ai_images_creator_history
  FOR DELETE
  USING (auth.uid() = user_id);

-- 创建索引以提高查询性能
CREATE INDEX idx_ai_images_creator_history_user_id ON ai_images_creator_history(user_id);
CREATE INDEX idx_ai_images_creator_history_created_at ON ai_images_creator_history(created_at);
CREATE INDEX idx_ai_images_creator_history_status ON ai_images_creator_history(status);

-- 创建触发器函数，自动更新updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 创建触发器
CREATE TRIGGER update_ai_images_creator_history_updated_at
    BEFORE UPDATE ON ai_images_creator_history
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();